---
apiVersion: v1
kind: Pod
metadata:
  name: sample-node-app
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: node-app
      image: sample-node-app:latest
      securityContext:
        runAsUser: 1000

